var ngh_compo = ngh_compo || {}
	
ngh_compo={
		
		r_con : ()=>{
			return  '<table class="highlight">'
			+'						<colgroup>'
			+'							<col width="26">'
			+'							<col width="26">'
			+'							<col width="94">'
			+'							<col width="98">'
			+'							<col width="58">'
			+'							<col width="*">'
			+'						</colgroup>'
			+'						<tbody>'
			+'							<tr class="down on">'
			+'								<td>'
			+'									<span class="bookmark"><a href="#">즐겨찾기</a></span>'
			+'								</td>'
			+'								<td class="cAlign">'
			+'									<a href="#">'
			+'										<div class="bar down">'
			+'											<span class="line" style="top: 13.3682px; height: 0.519935px;">-</span>'
			+'											<span class="box" style="top: 13.5px; height: 1px;">-</span>'
			+'										</div>'
			+'									</a>'
			+'								</td>'
			+'								<td class="tit">'
			+'									<a href="#">'
			+'								 		<strong>비트코인</strong>'
			+'									</a>'
			+'								 	<em>BTC<span>/KRW</span></em>'
			+'								 </td>'
			+'								<td class="price">'
			+'									<strong>6,122,000</strong>'
			+'									<span class=""></span>'
			+'								</td>'
			+'								<td class="percent">'
			+'									<p>-0.37%</p> '
			+'									<em>-23,000</em>'
			+'								</td>'
			+'								<td class="rAlign">'
			+'								<p>40,636<i>백만</i></p>'
			+'								</td>'
			+'							</tr>'
			+'						</tbody>'
			+'					</table>'
			

		},
		investment_trx:()=>{
			return '<div class="max">'
			+'<div class="rdo">'
			+'<a href="#" class=""><em>-</em>미체결</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="#" class="on"><em>-</em>체결</a>'
		+'</div>'
		+'<div>'
			+'<table class="ty02">'
				+'<colgroup>'
					+'<col width="96">'
					+'<col width="46">'
					+'<col width="114">'
					+'<col width="120">'
					+'<col width="*">'
				+'</colgroup>'
				+'<thead>'
					+'<tr>'
						+'<th>주문시간</th>'
						+'<th>구분</th>'
						+'<th>체결가격</th>'
						+'<th>체결수량</th>'
						+'<th>체결금액</th>'
					+'</tr>'
				+'</thead>'
			+'</table>'
			+'<div class="scrollB overflow" style="height: 293px;">'
				+'<div style="position: relative; overflow: hidden; width: 100%; height: 293px;">'
					+'<div style="position: absolute; top: 0px; left: 0px; right: 0px; bottom: 0px; overflow: scroll; margin-right: -17px; margin-bottom: -17px;">'
						+'<table class="ty02">'
							+'<colgroup>'
								+'<col width="96">'
								+'<col width="46">'
								+'<col width="114">'
								+'<col width="120">'
								+'<col width="*">'
							+'</colgroup>'
							+'<tbody>'
								+'<tr class="down">'
									+'<td><p>'
											+'12.30 <i>17:38</i>'
										+'</p></td>'
									+'<td>매도</td>'
									+'<td class="rAlign"><p>18,850,000</p></td>'
									+'<td class="rAlign"><p>0.01527253</p></td>'
									+'<td class="rAlign"><p>287,887</p></td>'
								+'</tr>'
								+'<tr class="up">'
									+'<td><p>'
											+'12.28 <i>09:50</i>'
										+'</p></td>'
									+'<td>매수</td>'
									+'<td class="rAlign"><p>21,810,000</p></td>'
									+'<td class="rAlign"><p>0.00996888</p></td>'
									+'<td class="rAlign"><p>217,422</p></td>'
								+'</tr>'
								+'<tr class="up">'
									+'<td><p>'
											+'12.28 <i>09:45</i>'
										+'</p></td>'
									+'<td>매수</td>'
									+'<td class="rAlign"><p>21,837,000</p></td>'
									+'<td class="rAlign"><p>0.00659460</p></td>'
									+'<td class="rAlign"><p>144,007</p></td>'
								+'</tr>'
								+'<tr class="down">'
									+'<td><p>'
											+'12.28 <i>09:23</i>'
										+'</p></td>'
									+'<td>매도</td>'
									+'<td class="rAlign"><p>21,923,000</p></td>'
									+'<td class="rAlign"><p>0.00658369</p></td>'
									+'<td class="rAlign"><p>144,334</p></td>'
								+'</tr>'
								+'<tr class="up">'
									+'<td><p>'
											+'12.28 <i>09:20</i>'
										+'</p></td>'
									+'<td>매수</td>'
									+'<td class="rAlign"><p>21,997,000</p></td>'
									+'<td class="rAlign"><p>0.00658369</p></td>'
									+'<td class="rAlign"><p>144,822</p></td>'
								+'</tr>'
								+'<tr class="down">'
									+'<td><p>'
											+'12.21 <i>14:15</i>'
										+'</p></td>'
									+'<td>매도</td>'
									+'<td class="rAlign"><p>23,155,000</p></td>'
									+'<td class="rAlign"><p>0.01171342</p></td>'
									+'<td class="rAlign"><p>271,224</p></td>'
								+'</tr>'
								+'<tr class="up">'
									+'<td><p>'
											+'12.19 <i>07:54</i>'
										+'</p></td>'
									+'<td>매수</td>'
									+'<td class="rAlign"><p>21,798,000</p></td>'
									+'<td class="rAlign"><p>0.01171342</p></td>'
									+'<td class="rAlign"><p>255,330</p></td>'
								+'</tr>'
								+'<tr class="down">'
									+'<td><p>'
											+'12.15 <i>12:47</i>'
										+'</p></td>'
									+'<td>매도</td>'
									+'<td class="rAlign"><p>20,111,000</p></td>'
									+'<td class="rAlign"><p>0.01053026</p></td>'
									+'<td class="rAlign"><p>211,774</p></td>'
								+'</tr>'
								+'<tr class="up">'
									+'<td><p>'
											+'12.13 <i>00:25</i>'
										+'</p></td>'
									+'<td>매수</td>'
									+'<td class="rAlign"><p>19,147,000</p></td>'
									+'<td class="rAlign"><p>0.01053026</p></td>'
									+'<td class="rAlign"><p>201,623</p></td>'
								+'</tr>'
								+'<tr class="down">'
									+'<td><p>'
											+'12.07 <i>14:04</i>'
										+'</p></td>'
									+'<td>매도</td>'
									+'<td class="rAlign"><p>19,000,000</p></td>'
									+'<td class="rAlign"><p>0.00667846</p></td>'
									+'<td class="rAlign"><p>126,890</p></td>'
								+'</tr>'
								+'<tr class="up">'
									+'<td><p>'
											+'12.07 <i>12:39</i>'
										+'</p></td>'
									+'<td>매수</td>'
									+'<td class="rAlign"><p>18,539,000</p></td>'
									+'<td class="rAlign"><p>0.00667846</p></td>'
									+'<td class="rAlign"><p>123,812</p></td>'
								+'</tr>'
								+'<tr class="down">'
									+'<td><p>'
											+'12.02 <i>11:30</i>'
										+'</p></td>'
									+'<td>매도</td>'
									+'<td class="rAlign"><p>13,000,000</p></td>'
									+'<td class="rAlign"><p>0.01669469</p></td>'
									+'<td class="rAlign"><p>217,030</p></td>'
								+'</tr>'
								+'<tr class="up">'
									+'<td><p>'
											+'12.02 <i>02:01</i>'
										+'</p></td>'
									+'<td>매수</td>'
									+'<td class="rAlign"><p>12,352,000</p></td>'
									+'<td class="rAlign"><p>0.01669469</p></td>'
									+'<td class="rAlign"><p>206,213</p></td>'
								+'</tr>'
							+'</tbody>'
						+'</table>'
					+'</div>'
					+'<div style="position: absolute; height: 6px; right: 2px; bottom: 2px; left: 2px; border-radius: 3px;">'
						+'<div style="position: relative; display: block; height: 100%; cursor: pointer; border-radius: inherit; background-color: rgba(0, 0, 0, 0.2); width: 0px;"></div>'
					+'</div>'
					+'<div style="position: absolute; width: 6px; right: 2px; bottom: 2px; top: 2px; border-radius: 3px;">'
						+'<div style="position: relative; display: block; width: 100%; cursor: pointer; border-radius: inherit; background-color: rgba(0, 0, 0, 0.2); height: 204px; transform: translateY(0px);"></div>'
					+'</div>'
				+'</div>'
			+'</div>'
		+'</div>'
	+'</div>'
		}
		
}